TYPE=VIEW
query=select `customs_zero`.`delivery`.`id_delivery` AS `id_delivery`,`customs_zero`.`delivery`.`delivery_time` AS `delivery_time`,`customs_zero`.`delivery`.`delivery_total_weight` AS `delivery_total_weight`,`customs_zero`.`delivery`.`delivery_total_volume` AS `delivery_total_volume`,`customs_zero`.`delivery`.`delivery_total_number` AS `delivery_total_number`,`customs_zero`.`delivery`.`deliverys_duty` AS `deliverys_duty`,`customs_zero`.`delivery`.`byuer` AS `byuer`,`customs_zero`.`delivery`.`provider` AS `provider`,`customs_zero`.`delivery`.`carrier` AS `carrier` from `customs_zero`.`delivery` order by year(`customs_zero`.`delivery`.`delivery_time`),month(`customs_zero`.`delivery`.`delivery_time`)
md5=a1c1a12f506c08c270400253be06eef4
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2015-11-20 13:00:38
create-version=1
source=SELECT * FROM delivery ORDER BY YEAR(delivery_time), MONTH(delivery_time)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `customs_zero`.`delivery`.`id_delivery` AS `id_delivery`,`customs_zero`.`delivery`.`delivery_time` AS `delivery_time`,`customs_zero`.`delivery`.`delivery_total_weight` AS `delivery_total_weight`,`customs_zero`.`delivery`.`delivery_total_volume` AS `delivery_total_volume`,`customs_zero`.`delivery`.`delivery_total_number` AS `delivery_total_number`,`customs_zero`.`delivery`.`deliverys_duty` AS `deliverys_duty`,`customs_zero`.`delivery`.`byuer` AS `byuer`,`customs_zero`.`delivery`.`provider` AS `provider`,`customs_zero`.`delivery`.`carrier` AS `carrier` from `customs_zero`.`delivery` order by year(`customs_zero`.`delivery`.`delivery_time`),month(`customs_zero`.`delivery`.`delivery_time`)
