TYPE=VIEW
query=select sum(`customs_zero`.`duty`.`duty_total_size`) AS `DTS` from `customs_zero`.`duty`
md5=f45d9a2cfdad9b721e50a9664d5af2dd
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2015-11-20 12:54:54
create-version=1
source=SELECT SUM(duty_total_size) AS DTS FROM duty
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select sum(`customs_zero`.`duty`.`duty_total_size`) AS `DTS` from `customs_zero`.`duty`
