TYPE=VIEW
query=select `customs_zero`.`goods`.`id_good` AS `id_good`,`customs_zero`.`goods`.`good_name` AS `good_name`,`customs_zero`.`goods`.`good_weight` AS `good_weight`,`customs_zero`.`goods`.`good_amount` AS `good_amount`,`customs_zero`.`goods`.`good_volume` AS `good_volume` from `customs_zero`.`goods` where ((`customs_zero`.`goods`.`good_name` like \'%5\') and (`customs_zero`.`goods`.`good_weight` between 5 and 10))
md5=4984586e6e4d216451c84ce84d5a82cb
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2015-11-20 12:40:43
create-version=1
source=SELECT * FROM goods WHERE goods.good_name LIKE \'%5\' AND goods.good_weight BETWEEN 5 AND 10
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `customs_zero`.`goods`.`id_good` AS `id_good`,`customs_zero`.`goods`.`good_name` AS `good_name`,`customs_zero`.`goods`.`good_weight` AS `good_weight`,`customs_zero`.`goods`.`good_amount` AS `good_amount`,`customs_zero`.`goods`.`good_volume` AS `good_volume` from `customs_zero`.`goods` where ((`customs_zero`.`goods`.`good_name` like \'%5\') and (`customs_zero`.`goods`.`good_weight` between 5 and 10))
