TYPE=VIEW
query=select `customs_zero`.`goods`.`id_good` AS `id_good`,`customs_zero`.`goods`.`good_name` AS `good_name`,`customs_zero`.`goods`.`good_weight` AS `good_weight`,`customs_zero`.`goods`.`good_amount` AS `good_amount`,`customs_zero`.`goods`.`good_volume` AS `good_volume` from `customs_zero`.`goods` where `customs_zero`.`goods`.`id_good` in (select `customs_zero`.`ratio_duty_goods`.`good_id` from `customs_zero`.`ratio_duty_goods` where (`customs_zero`.`ratio_duty_goods`.`good_id` > 55))
md5=7b1d259f2a42bde3a13ff027e4470522
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2015-11-20 14:28:58
create-version=1
source=SELECT * FROM goods WHERE id_good IN (SELECT good_id FROM ratio_duty_goods WHERE ratio_duty_goods.good_id>55)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `customs_zero`.`goods`.`id_good` AS `id_good`,`customs_zero`.`goods`.`good_name` AS `good_name`,`customs_zero`.`goods`.`good_weight` AS `good_weight`,`customs_zero`.`goods`.`good_amount` AS `good_amount`,`customs_zero`.`goods`.`good_volume` AS `good_volume` from `customs_zero`.`goods` where `customs_zero`.`goods`.`id_good` in (select `customs_zero`.`ratio_duty_goods`.`good_id` from `customs_zero`.`ratio_duty_goods` where (`customs_zero`.`ratio_duty_goods`.`good_id` > 55))
